/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Pcp
#define HEADER_Pcp
#include <pcp/pmapi.h>
extern int pcp_context;
int lookupMetric(char *metric, pmAtomValue *atom, int type, int inst);

#endif
