/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_PcpProcessList
#define HEADER_PcpProcessList
/*
htop - PcpProcessList.h
(C) 2014 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/


int get_ncpu(void);
ProcessList* ProcessList_new(UsersTable* usersTable, Hashtable* pidWhiteList, uid_t userId);

void ProcessList_delete(ProcessList* this);

void ProcessList_goThroughEntries(ProcessList* super);

void PcpProcessList_scan(ProcessList* this);

#endif
