/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_UnsupportedProcess
#define HEADER_UnsupportedProcess
/*
htop - UnsupportedProcess.h
(C) 2015 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Settings.h"



Process* UnsupportedProcess_new(Settings* settings);

void Process_delete(Object* cast);

#endif
